### ISSUE TITLE
Feedback style

### ISSUE THREAD

**Issue by roberrrt-s** [robert-hoekstra/frontend-data#1]
Hi Robert, je gebruikt naar mijn idee nogal wat verschillende functie soorten door elkaar (`var x = () => {}` en `function() {}`. Liever wat meer consistentie. Verder gebeurd er in app.js heel veel momenteel, het is vaak netter om verschillende type functies in verschillende bestanden te gebruiken, en ik zie nog wel wat kansen daarin voor je main javascript bestand. Veel succes verder!

**Comment by robert-hoekstra** [comment]
Thanks Robert! Ik ga er naar kijken!
